name: Publish To NPM

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn

      - name: Run Tests
        run: |
          yarn test

  prepares-for-publish:
    runs-on: ubuntu-lastest

    needs: test

    steps:
      - name: Build
        run: |
          tsc

      - name: Move package.json To Lib Folder
        run: |
          mv ${{ GITHUB_WORKSPACE }}/package.json ${{ GITHUB_WORKSPACE }}/lib/package.json

  publish-to-npm:
    runs-on: ubuntu-lastest

    steps:
      - name: Publish To NPM
        uses: pascalgn/npm-publish-action@1.3.6
        with:
          create_tag: false
          workspace: ${{ GITHUB_WORKSPACE }}/lib
          publish_command: yarn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
