name: Publish To NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn

      - name: Run Tests
        run: |
          yarn test

      - name: Build
        run: |
          yarn pipeline

      # Publish to NPM
      - uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@techmmunity"
          npm config list
          npm publish dist --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Publish to GitHub Package Registry
      - uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@techmmunity"

      - name: Publish to GitHub Package Registry
        run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
