name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          yarn
      - name: Run Tests
        run: |
          yarn test
